version: '3'
services:
  monitor:
    image: "php:7.2-apache"
    restart: "unless-stopped"
    ports:
     - "80:80"
    volumes:
     - "/opt/nanoNodeMonitor:/var/www/html"
  nanonode:
    image: "nanocurrency/nano"
    restart: "unless-stopped"
    ports:
     - "7075:7075/udp"
     - "7075:7075"
     - ":::7076:7076"
    volumes:
     - "~:/root"