version: '3'
services:
  nanonodemonitor:
    image: "php:7.2-apache"
    ports:
     - "80:80"
    volumes:
     - "/opt/nanoNodeMonitor:/var/www/html"
  nanonode:
    image: "nanocurrency/nano"
    restart: "unless-stopped"
    ports:
     - "7075:7075/udp"
     - "7075:7075"
     - "127.0.0.1:7076:7076"
    volumes:
     - "~:/root"